[project]
name = "timestamp"
version = "0.1.0"
description = "simple timestamp generator - just press space"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.54.0",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "numpy>=2.4.2",
    "scipy>=1.17.1",
]
